<a href="https://colab.research.google.com/github/dhamvi01/Python-Numpy/blob/master/Python-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



 **Numpy: Import numpy and prepare an array**




**Create Numpy array**

In [0]:
import numpy as np

np.arange(10) + 1

np.arange(100)

np.random.randn(10)

array([-1.28172514,  0.2428014 , -0.11357723, -0.58358435,  0.65207337,
        0.3753053 ,  1.51568411,  1.50363717,  0.60180436,  0.03744701])

**1D, 2D and 3D Arrays**

In [0]:
import numpy as np

a  = np.array([1,2,3,4])
b = np.array([(1,2,3),(4,5,6)])
c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])

a[0]
print(b)
b[0][0]
b[1][:2]

print(c)
c[0][0][1]

b

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[1, 2, 3],
       [4, 5, 6]])

**Numpy Data Types**

In [0]:
a = np.array([1,2,3.3])
a.dtype
b = a.astype(int)
b
b.dtype

a = np.array([1,2,3.3],dtype='int')
a.dtype
a

array([1, 2, 3])

In [0]:
a.dtype

dtype('int64')

**Auto create Numpy Array**

In [0]:
a = np.zeros((3,4))
#a.dtype
a
a[1] = 10
a

np.ones((3,3,4))

np.arange(20)

np.arange(1,20,2)

#np.linspace(0,2,5)

np.full((3,3),'a')

np.eye(5)

np.random.randn(10)

np.empty((4,3))

array([[ 0.,  0.,  0.],
       [ 0., 10., 10.],
       [10., 10.,  0.],
       [ 0.,  0.,  0.]])

In [0]:
a = np.array([[1,2,3], [4,5,6]])

a.shape

a.ndim

len(a)

a.size

a.dtype

b = a.astype(float)
b



array([[1., 2., 3.],
       [4., 5., 6.]])

**How to get more information**

In [0]:
np.info(np.arange)
np.info(np.random)

In [0]:
import numpy as np

a = np.array([1,2,3,4])

a

a = np.arange(10)
a

a.size
a.ndim


1

**Arithmetic Operation**

In [0]:
a = np.array([[1,2,3],[4,5,6]])
a + 10

a * a

1/a

a-a

a[0,1] = 10
a[0,0] = a[0,0] + 10
a**2


array([[121, 100,   9],
       [ 16,  25,  36]])

In [0]:
a = np.array([10,20,30])
b = np.array([4,5,2])

a + b
a - b
a * b
a / b

np.exp(a)
np.sqrt(a)
np.log(a)

array([2.30258509, 2.99573227, 3.40119738])

**Comparision Operators**

In [0]:
a = np.array([10,20,30])
b = np.array([10,20,30])

a > 15

a == b
a != b
a >= b
a <= b

np.array_equal(a,b)

True

**Sort an Array**

In [0]:
a = [11,12,1,2,3,4,5,10]
a.sort(reverse=True)
a

[12, 11, 10, 5, 4, 3, 2, 1]

In [0]:
a = np.array([1,2,3,4,5,6,1,2,4,10,5,6])
#a.sort()
print(a)

#a[2::3] = 300
#a

a[::-1].sort()
a



[ 1  2  3  4  5  6  1  2  4 10  5  6]


array([10,  6,  6,  5,  5,  4,  4,  3,  2,  2,  1,  1])

**Aggregation Functions**

In [0]:
a = np.arange(10)
a

sum(a)
min(a)
max(a)

np.max(a)
np.min(a)

a.cumsum()

a.mean()

4.5

In [0]:
a = np.array([1,2,3,4])

b = a

a[1] = 400

b[2] = 300

a



array([  1, 400, 300,   4])

**Copy an Array**

In [0]:
a = np.array([1,2,3,4])

b = a.copy()

a[1] = 400

b[2] = 300

a

array([  1, 400,   3,   4])

**Slicing and Dicing**

In [0]:
a = np.array([[1,2,3],[4,5,6]])
a

a[0]
a[0][1]
a[0,1]

a[0,1] = 100
a

a[1] = 10
a

a[0,1:]

b = a[1]
b

a[-1]


array([10, 10, 10])

**Data Transformation**

In [0]:
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print(a)
c = a.T
c

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [0]:
a = np.arange(12).reshape(4,3) + 1
a
#b = a.reshape(4,3)
#b
b = a.reshape(6,2)
b

c = a.reshape(-1,1)
c

c = a.reshape(12,1)
c

print(a)
d = np.resize(a,(2,2))
d


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[1, 2],
       [3, 4]])